# Generated by Django 3.1.4 on 2020-12-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentMode', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
