# Generated by Django 3.1.4 on 2020-12-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='userId',
            field=models.IntegerField(null=True),
        ),
    ]
